-- MySQL Script generated by MySQL Workbench
-- 07/18/16 19:51:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Administrativo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Administrativo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Administrativo` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema tms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tms` DEFAULT CHARACTER SET utf8 ;
USE `Administrativo` ;

-- -----------------------------------------------------
-- Table `tms`.`tbl_mobiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tms`.`tbl_mobiles` (
  `id_mobiles` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_company` SMALLINT(5) NOT NULL,
  `id_agreements` BIGINT(20) NOT NULL,
  `name` VARCHAR(70) NULL DEFAULT NULL,
  `identification` VARCHAR(30) NOT NULL DEFAULT '',
  `imei` VARCHAR(50) NULL DEFAULT NULL,
  `sim_id` VARCHAR(20) NULL DEFAULT NULL,
  `sim_pin` VARCHAR(20) NULL DEFAULT NULL,
  `sim_puk` VARCHAR(20) NULL DEFAULT NULL,
  `sim_imsi` VARCHAR(20) NULL DEFAULT NULL,
  `sim_apn` VARCHAR(50) NULL DEFAULT NULL,
  `sim_username` VARCHAR(50) NULL DEFAULT NULL,
  `sim_password` VARCHAR(50) NULL DEFAULT NULL,
  `owner` VARCHAR(45) NULL DEFAULT NULL,
  `owner_name` VARCHAR(200) NULL DEFAULT NULL,
  `vehicle_identification_number` VARCHAR(20) NULL DEFAULT NULL,
  `suspension_level` TINYINT(1) NOT NULL COMMENT 'el nivel de suspencion en el que se encuentra el dispositivo',
  `apportionment` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'tipo de prorrateo',
  `created_by` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `created_from` VARCHAR(50) NOT NULL,
  `modified_by` BIGINT(20) UNSIGNED NOT NULL,
  `modified_at` DATETIME NOT NULL,
  `modified_from` VARCHAR(50) NOT NULL,
  `delete_mark` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_mobiles`, `id_company`, `identification`, `id_agreements`))
ENGINE = MyISAM
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = latin1
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `tms`.`tbl_companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tms`.`tbl_companies` (
  `id_company` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tax_id` BIGINT(15) UNSIGNED NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `id_parent` SMALLINT(5) NOT NULL,
  `latitude` FLOAT NOT NULL,
  `longitude` FLOAT NOT NULL,
  `timezone` VARCHAR(5) NULL DEFAULT NULL,
  `address` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(70) NOT NULL,
  `website` VARCHAR(70) NULL DEFAULT NULL,
  `contact` VARCHAR(70) NOT NULL,
  `fault_intervals` VARCHAR(10) NULL DEFAULT NULL,
  `support_mail` VARCHAR(100) NULL DEFAULT NULL,
  `support_name` VARCHAR(100) NOT NULL,
  `run_driver_qualification` TINYINT(1) NULL DEFAULT NULL,
  `webservice_ip` VARCHAR(20) NOT NULL COMMENT 'ip autorizada para ingresar al webservice',
  `webservice_last_update` DATETIME NOT NULL COMMENT 'ultima consulta por el web service',
  `company_status` TINYINT(4) NULL DEFAULT NULL COMMENT 'campo para identificar el estado de la compañia con relacion al crm',
  `created_by` SMALLINT(5) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `created_from` VARCHAR(50) NOT NULL,
  `modified_by` BIGINT(20) UNSIGNED NOT NULL,
  `modified_at` DATETIME NOT NULL,
  `modified_from` VARCHAR(50) NOT NULL,
  `delete_mark` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_company`),
  INDEX `tax_id` (`tax_id` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Administrativo`.`tbl_billing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Administrativo`.`tbl_billing` (
  `id_billing` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'Id facturación activo, único.',
  `id_servers` SMALLINT(5) NOT NULL COMMENT 'Dato de la tabla servidores, cuando se cree el vehículo, envia id, desde que servidor fue enviado 1,2 o 3.',
  `id_mobiles` BIGINT(20) NOT NULL COMMENT 'Dato de la tabla mobiles, cuando se crea el vehículo envia el id asignado por tbl_mobiles a este campo.',
  `name` VARCHAR(30) NOT NULL DEFAULT NULL COMMENT 'Dato de la tabla mobiles, cuando se crea el vehículo envia el nombre diligenciado en tbl_mobiles a este campo.',
  `identification` VARCHAR(30) NOT NULL DEFAULT ' COMMENT 'Dato de la tabla mobiles, cuando se crea el vehículo envia la identificación diligenciado en tbl_mobiles a este campo.',
  `sim_imsi` VARCHAR(20) NOT NULL DEFAULT ' COMMENT 'Dato de la tabla mobiles, cuando se crea el vehículo envia el imsi diligenciado en tbl_mobiles a este campo.',
  `id_company` SMALLINT(5) NOT NULL COMMENT 'Dato de la tabla mobiles, cuando se crea el vehículo envia compañia a la cual esta reportando diligenciado en tbl_mobiles a este campo.',
  `suspension_level` TINYINT(1) NOT NULL COMMENT 'Dato de la tabla mobiles, cuando se cambia el estado se debe actualizar automáticamente en esta tabla',
  `id_owner` BIGINT(20) NOT NULL COMMENT 'Dato de la tabla contrato, que esta asociado con el código de contrato --- otra opcion es que lo diligencie el usuario, enlazando tablas propietario y compañia, que es lo que haria la tabla contratos',
  `agreement_code` BIGINT(20) NOT NULL COMMENT 'Usuario diligencia campo, de la tabla contratos',
  `id_billing_period` TINYINT(1) NOT NULL COMMENT 'Usuario Ingresa dato, de la tabla billing_period',
  `time_to_billing` VARCHAR(50) NOT NULL DEFAULT  COMMENT 'Inicialmente que el usuario ingrese dato, pero se cambiara para que sea automático y dependa de más parametros como el contrato...etc',
  `id_plans` VARCHAR(10) NOT NULL COMMENT 'Información que se debe traer desde el contrato; el campo se llena en contrto y se tiiene una tabla con los planes',
  `id_tariff` TINYINT(1) NOT NULL COMMENT 'Usuario ingresa dato para cada activo, dato de la tabla tarifas.',
  `radicated` VARCHAR(20) NOT NULL COMMENT 'Usuario ingresa si es por medio electronico o físico, talvez crear tabla con FISICO, ELECTRONICO',
  `id_due_date` SMALLINT(5) NOT NULL,
  `support_name` VARCHAR(100) NOT NULL DEFAULT ' COMMENT 'Dato desde la tabla compañias',
  `adress` VARCHAR(45) NOT NULL DEFAULT ' COMMENT 'Usuario ingresa datos.',
  `case` INT(10) NOT NULL DEFAULT 0 COMMENT 'Usuario ingresa dato para seguimiento del activo',
  `created_by` SMALLINT(5) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `created_from` VARCHAR(50) NOT NULL,
  `modified_by` BIGINT(20) NOT NULL,
  `modified_at` DATETIME NOT NULL,
  `modified_from` VARCHAR(50) NOT NULL,
  `delete_mark` TINYINT(1) UNSIGNED NOT NULL COMMENT 'Dato de la tabla mobiles, cuando se cambia el estado se debe actualizar automáticamente en esta tabla',
  PRIMARY KEY (`id_billing`, `id_servers`, `id_mobiles`, `name`, `identification`, `sim_imsi`, `id_company`),
  INDEX `fk_tbl_billing_tbl_mobiles_idx` (`id_mobiles` ASC),
  INDEX `fk_tbl_billing_tbl_mobiles1_idx` (`name` ASC),
  INDEX `fk_tbl_billing_tbl_mobiles3_idx` (`sim_imsi` ASC),
  INDEX `fk_tbl_billing_tbl_mobiles4_idx` (`identification` ASC),
  INDEX `fk_tbl_billing_tbl_mobiles5_idx` (`id_company` ASC),
  INDEX `fk_tbl_billing_tbl_mobiles6_idx` (`suspension_level` ASC),
  INDEX `fk_tbl_billing_tbl_mobiles7_idx` (`delete_mark` ASC),
  INDEX `fk_tbl_billing_tbl_companies1_idx` (`support_name` ASC),
  CONSTRAINT `fk_tbl_billing_tbl_mobiles`
    FOREIGN KEY (`id_mobiles`)
    REFERENCES `tms`.`tbl_mobiles` (`id_mobiles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_billing_tbl_mobiles1`
    FOREIGN KEY (`name`)
    REFERENCES `tms`.`tbl_mobiles` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_billing_tbl_mobiles3`
    FOREIGN KEY (`sim_imsi`)
    REFERENCES `tms`.`tbl_mobiles` (`sim_imsi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_billing_tbl_mobiles4`
    FOREIGN KEY (`identification`)
    REFERENCES `tms`.`tbl_mobiles` (`identification`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_billing_tbl_mobiles5`
    FOREIGN KEY (`id_company`)
    REFERENCES `tms`.`tbl_mobiles` (`id_company`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_billing_tbl_mobiles6`
    FOREIGN KEY (`suspension_level`)
    REFERENCES `tms`.`tbl_mobiles` (`suspension_level`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_billing_tbl_mobiles7`
    FOREIGN KEY (`delete_mark`)
    REFERENCES `tms`.`tbl_mobiles` (`delete_mark`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_billing_tbl_companies1`
    FOREIGN KEY (`support_name`)
    REFERENCES `tms`.`tbl_companies` (`support_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Administrativo`.`tbl_billing_period`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Administrativo`.`tbl_billing_period` (
  `id_billing_period` TINYINT(1) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `created_by` BIGINT(20) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `created_from` VARCHAR(50) NOT NULL,
  `modified_by` BIGINT(20) NOT NULL,
  `modified_at` DATETIME NOT NULL,
  `modified_from` VARCHAR(50) NOT NULL,
  `delete_mark` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_billing_period`))
ENGINE = MyISAM
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Administrativo`.`tbl_servers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Administrativo`.`tbl_servers` (
  `id_servers` SMALLINT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `ip` VARCHAR(50) NOT NULL,
  `created_by` BIGINT(20) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `created_from` VARCHAR(50) NOT NULL,
  `modified_by` BIGINT(20) NOT NULL,
  `modified_at` DATETIME NOT NULL,
  `modified_from` VARCHAR(50) NOT NULL,
  `delete_mark` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_servers`))
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Administrativo`.`tbl_suspension_level`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Administrativo`.`tbl_suspension_level` (
  `id_suspension_level` SMALLINT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `created_by` BIGINT(20) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `created_from` VARCHAR(20) NOT NULL,
  `modified_by` BIGINT(20) NOT NULL,
  `modified_at` DATETIME NOT NULL,
  `modified_from` VARCHAR(50) NOT NULL,
  `delete_mark` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_suspension_level`))
ENGINE = MyISAM
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Administrativo`.`tbl_plans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Administrativo`.`tbl_plans` (
  `id_plans` INT(10) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `cost` FLOAT NOT NULL,
  `created_by` BIGINT(20) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `created_from` VARCHAR(50) NOT NULL,
  `modified_by` BIGINT(20) NOT NULL,
  `modified_at` DATETIME NOT NULL,
  `modified_from` VARCHAR(50) NOT NULL,
  `delete_mark` TINYINT(1) NOT NULL,
  INDEX `fk_tbl_plans_tbl_billing1_idx` (`id_plans` ASC),
  PRIMARY KEY (`id_plans`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Administrativo`.`tbl_agreements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Administrativo`.`tbl_agreements` (
  `id_agreements` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `id_owner` INT(10) NOT NULL DEFAULT NULL COMMENT 'Este dato es traido de tbl_companies o tbl_owners dependiendo de los diferentes casos que se den, si ya existe en plataforma, o si no tiene plataforma',
  `name` VARCHAR(50) NOT NULL,
  `identification` INT(15) NOT NULL,
  `address` VARCHAR(50) NOT NULL,
  `id_kind_of_person` TINYINT(1) NOT NULL,
  `agreement_start` DATE NOT NULL,
  `agreement_end` DATE NOT NULL,
  `agreement_mode` TINYINT(2) NOT NULL,
  `id_collection_type` TINYINT(1) NOT NULL,
  `billing_period` TINYINT(2) NOT NULL,
  `id_plans` SMALLINT(5) NOT NULL COMMENT 'Dato de la tabla planes, usuario ingresa opción',
  `agreement_code` TINYINT(1) NOT NULL COMMENT 'código que esta en el contrato, lo utiliza la tabla facturacion',
  `purchase_order` TINYINT(1) NOT NULL COMMENT 'Orden de compra lo utiliza también ',
  `extension` TINYINT(1) NOT NULL,
  `created_by` BIGINT(20) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `created_from` VARCHAR(50) NOT NULL,
  `modified_by` BIGINT(20) NOT NULL,
  `modified_at` DATETIME NOT NULL,
  `modified_from` VARCHAR(50) NOT NULL,
  `delete_mark` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_agreements`, `id_owner`, `agreement_code`),
  INDEX `fk_tbl_agreements_tbl_billing1_idx` (`id_owner` ASC),
  INDEX `fk_tbl_agreements_tbl_billing2_idx` (`agreement_code` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 1272
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Administrativo`.`tbl_agreement_mode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Administrativo`.`tbl_agreement_mode` (
  `id_agreement_mode` TINYINT(1) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `created_by` BIGINT(20) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `created_from` VARCHAR(50) NOT NULL,
  `modified_by` BIGINT(20) NOT NULL,
  `modified_at` DATETIME NOT NULL,
  `modified_from` VARCHAR(50) NOT NULL,
  `delete_mark` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_agreement_mode`))
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Administrativo`.`tbl_tariff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Administrativo`.`tbl_tariff` (
  `id_tariff` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Tabla la cual tendra las tarifas con los diferentes precios. Ej: Normal = 60000, la llena el usuario con un formulario y va añadiendo seún necesidades',
  `name_tariff` VARCHAR(20) NOT NULL,
  `price` BIGINT(20) NOT NULL,
  `created_by` SMALLINT(5) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `created_from` VARCHAR(50) NOT NULL,
  `modified_by` BIGINT(20) NOT NULL,
  `modified_at` DATETIME NOT NULL,
  `modified_from` VARCHAR(50) NOT NULL,
  `delete_mark` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_tariff`),
  CONSTRAINT `fk_tbl_tariff_tbl_billing1`
    FOREIGN KEY (`id_tariff`)
    REFERENCES `Administrativo`.`tbl_billing` (`id_tariff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Administrativo`.`tbl_due_date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Administrativo`.`tbl_due_date` (
  `id_due_date` SMALLINT(5) NOT NULL AUTO_INCREMENT COMMENT 'Tabla de vencimiento, contiene por ejemplo si es 15 días, 30 días, 45 días...etc.',
  `name_due_date` VARCHAR(50) NOT NULL,
  `created_by` SMALLINT(5) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `created_from` VARCHAR(50) NOT NULL,
  `modified_by` BIGINT(20) NOT NULL,
  `modified_at` DATETIME NOT NULL,
  `modified_from` VARCHAR(50) NOT NULL,
  `delete_mark` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_due_date`),
  CONSTRAINT `fk_tbl_due_date_tbl_billing1`
    FOREIGN KEY (`id_due_date`)
    REFERENCES `Administrativo`.`tbl_billing` (`id_due_date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Administrativo`.`owners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Administrativo`.`owners` (
  `id_owners` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Tabla donde se encuentran todas las entidades a las que se les genera factura, es decir tienen contrato....',
  `tax_id` VARCHAR(50) NOT NULL COMMENT 'Este campo se llena con la cedula o el NIT, depende el tipo de persona',
  `name` VARCHAR(50) NOT NULL COMMENT 'Nombre y apellido',
  `type_person` TINYINT(1) UNSIGNED NOT NULL COMMENT 'Tipo de persona Ej: 1 = Natural 2 = Jurídica',
  `address` VARCHAR(100) NOT NULL COMMENT 'Dirección a erradicar factura',
  `phone` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'Telefono celular o fijo',
  `email` VARCHAR(70) NOT NULL COMMENT 'Correo electrónico',
  `website` VARCHAR(70) NULL DEFAULT NULL COMMENT 'Sitio Web, si se tiene',
  `contact` VARCHAR(70) NOT NULL COMMENT 'Numero de contacto, celular',
  `create_by` BIGINT(20) UNSIGNED NOT NULL,
  `create_at` DATETIME NOT NULL,
  `create_from` VARCHAR(50) NOT NULL,
  `modified_by` BIGINT(20) UNSIGNED NOT NULL,
  `modified_at` DATETIME NOT NULL,
  `modified_from` VARCHAR(50) NOT NULL,
  `delete_mark` SMALLINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_owners`, `tax_id`),
  INDEX `tax_id` (`tax_id` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Administrativo`.`tbl_collection_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Administrativo`.`tbl_collection_type` (
  `id_collection_type` TINYINT(1) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `created_by` BIGINT(20) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `created_from` VARCHAR(50) NOT NULL,
  `modified_by` BIGINT(20) NOT NULL,
  `modified_at` DATETIME NOT NULL,
  `modified_from` VARCHAR(50) NOT NULL,
  `delete_mark` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_collection_type`))
ENGINE = MyISAM
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Administrativo`.`tbl_kind_of_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Administrativo`.`tbl_kind_of_person` (
  `id_kind_of_person` TINYINT(1) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `created_by` BIGINT(20) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `created_from` VARCHAR(50) NOT NULL,
  `modified_by` BIGINT(20) NOT NULL,
  `modified_at` DATETIME NOT NULL,
  `modified_from` VARCHAR(50) NOT NULL,
  `delete_mark` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_kind_of_person`))
ENGINE = MyISAM
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = latin1;

USE `tms` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
